-- 知识擂台 100 道题库种子数据
-- 依赖：019_arena_questions_schema.sql 已执行

INSERT INTO arena_questions (id, topic, subtopic, title, options, answer, created_at) VALUES
('q001', '历史', '朝代故事', '四大发明不包括以下哪项？', '["A. 造纸术", "B. 火药", "C. 望远镜", "D. 指南针"]', 'C', extract(epoch from now())::bigint),
('q002', '历史', '名人传记', '秦始皇统一了以下哪项？', '["A. 文字", "B. 货币", "C. 车轨", "D. 以上都是"]', 'D', extract(epoch from now())::bigint),
('q003', '历史', '朝代故事', '唐朝的都城是？', '["A. 洛阳", "B. 长安", "C. 南京", "D. 北京"]', 'B', extract(epoch from now())::bigint),
('q004', '历史', '名人传记', '发明活字印刷术的是？', '["A. 蔡伦", "B. 毕昇", "C. 张衡", "D. 祖冲之"]', 'B', extract(epoch from now())::bigint),
('q005', '历史', '朝代故事', '丝绸之路最繁盛的时期是？', '["A. 唐朝", "B. 汉朝", "C. 明朝", "D. 清朝"]', 'A', extract(epoch from now())::bigint),
('q006', '历史', '名人传记', '《史记》的作者是？', '["A. 司马光", "B. 司马迁", "C. 班固", "D. 陈寿"]', 'B', extract(epoch from now())::bigint),
('q007', '历史', '朝代故事', '长城最早大规模修筑是在哪个朝代？', '["A. 秦朝", "B. 汉朝", "C. 唐朝", "D. 明朝"]', 'A', extract(epoch from now())::bigint),
('q008', '历史', '名人传记', '郑和下西洋发生在哪个朝代？', '["A. 元朝", "B. 明朝", "C. 清朝", "D. 宋朝"]', 'B', extract(epoch from now())::bigint),
('q009', '历史', '朝代故事', '科举制度正式确立是在？', '["A. 隋朝", "B. 唐朝", "C. 宋朝", "D. 汉朝"]', 'A', extract(epoch from now())::bigint),
('q010', '历史', '名人传记', '发明地动仪的是？', '["A. 张衡", "B. 祖冲之", "C. 郭守敬", "D. 李时珍"]', 'A', extract(epoch from now())::bigint),
('q011', '历史', '朝代故事', '甲骨文主要刻在什么上？', '["A. 竹简", "B. 龟甲和兽骨", "C. 纸张", "D. 石头"]', 'B', extract(epoch from now())::bigint),
('q012', '历史', '名人传记', '《本草纲目》的作者是？', '["A. 华佗", "B. 李时珍", "C. 孙思邈", "D. 张仲景"]', 'B', extract(epoch from now())::bigint),
('q013', '历史', '朝代故事', '中国第一个统一的封建王朝是？', '["A. 夏朝", "B. 商朝", "C. 周朝", "D. 秦朝"]', 'D', extract(epoch from now())::bigint),
('q014', '历史', '名人传记', '造纸术的改进归功于？', '["A. 毕昇", "B. 蔡伦", "C. 张衡", "D. 祖冲之"]', 'B', extract(epoch from now())::bigint),
('q015', '历史', '朝代故事', '「贞观之治」指的是哪位皇帝？', '["A. 李渊", "B. 李世民", "C. 李隆基", "D. 武则天"]', 'B', extract(epoch from now())::bigint),
('q016', '篮球', '规则常识', '篮球比赛每队上场几人？', '["A. 4 人", "B. 5 人", "C. 6 人", "D. 7 人"]', 'B', extract(epoch from now())::bigint),
('q017', '篮球', '规则常识', '三分线外投进一球得几分？', '["A. 1 分", "B. 2 分", "C. 3 分", "D. 4 分"]', 'C', extract(epoch from now())::bigint),
('q018', '篮球', '球星故事', 'NBA 中「飞人」指的是谁？', '["A. 科比", "B. 乔丹", "C. 詹姆斯", "D. 库里"]', 'B', extract(epoch from now())::bigint),
('q019', '篮球', '规则常识', '罚球进一球得几分？', '["A. 0 分", "B. 1 分", "C. 2 分", "D. 3 分"]', 'B', extract(epoch from now())::bigint),
('q020', '篮球', '规则常识', '一节比赛通常多少分钟？', '["A. 8 分钟", "B. 10 分钟", "C. 12 分钟", "D. 15 分钟"]', 'C', extract(epoch from now())::bigint),
('q021', '篮球', '球星故事', '姚明曾效力于哪支 NBA 球队？', '["A. 湖人", "B. 火箭", "C. 勇士", "D. 热火"]', 'B', extract(epoch from now())::bigint),
('q022', '篮球', '规则常识', '带球走步在规则里叫做？', '["A. 走步", "B. 二次运球", "C. 违例", "D. 犯规"]', 'A', extract(epoch from now())::bigint),
('q023', '篮球', '规则常识', '篮球的直径大约多少厘米？', '["A. 约 20 cm", "B. 约 24 cm", "C. 约 28 cm", "D. 约 32 cm"]', 'B', extract(epoch from now())::bigint),
('q024', '篮球', '球星故事', '「小皇帝」指的是哪位球星？', '["A. 乔丹", "B. 詹姆斯", "C. 杜兰特", "D. 库里"]', 'B', extract(epoch from now())::bigint),
('q025', '篮球', '规则常识', '全场篮球比赛一般共几节？', '["A. 2 节", "B. 4 节", "C. 6 节", "D. 8 节"]', 'B', extract(epoch from now())::bigint),
('q026', '自然', '动物世界', '熊猫主要吃什么？', '["A. 肉", "B. 竹子", "C. 水果", "D. 鱼"]', 'B', extract(epoch from now())::bigint),
('q027', '自然', '动物世界', '企鹅生活在哪个洲？', '["A. 非洲", "B. 南极洲", "C. 亚洲", "D. 欧洲"]', 'B', extract(epoch from now())::bigint),
('q028', '自然', '植物天地', '向日葵会朝向哪里？', '["A. 北方", "B. 南方", "C. 太阳方向", "D. 地面"]', 'C', extract(epoch from now())::bigint),
('q029', '自然', '天气气候', '雷雨时先看到闪电还是先听到雷声？', '["A. 同时", "B. 先闪电", "C. 先雷声", "D. 不一定"]', 'B', extract(epoch from now())::bigint),
('q030', '自然', '动物世界', '蜜蜂采蜜是为了？', '["A. 玩耍", "B. 酿蜜和传粉", "C. 喝水", "D. 搬家"]', 'B', extract(epoch from now())::bigint),
('q031', '自然', '天气气候', '一年有几个季节？', '["A. 2 个", "B. 3 个", "C. 4 个", "D. 5 个"]', 'C', extract(epoch from now())::bigint),
('q032', '自然', '植物天地', '植物进行光合作用需要什么？', '["A. 阳光、水、二氧化碳", "B. 只有阳光", "C. 只有水", "D. 只有土壤"]', 'A', extract(epoch from now())::bigint),
('q033', '自然', '动物世界', '长颈鹿的脖子为什么那么长？', '["A. 为了好看", "B. 便于吃高处的树叶", "C. 为了跑步", "D. 天生如此"]', 'B', extract(epoch from now())::bigint),
('q034', '自然', '天气气候', '彩虹有几种颜色？', '["A. 5 种", "B. 6 种", "C. 7 种", "D. 8 种"]', 'C', extract(epoch from now())::bigint),
('q035', '自然', '动物世界', '蝙蝠是鸟类吗？', '["A. 是", "B. 不是，是哺乳动物", "C. 是昆虫", "D. 是爬行动物"]', 'B', extract(epoch from now())::bigint),
('q036', '自然', '植物天地', '仙人掌的刺其实是？', '["A. 叶子", "B. 根", "C. 茎", "D. 花"]', 'A', extract(epoch from now())::bigint),
('q037', '自然', '天气气候', '水在多少度会结冰？', '["A. -1℃", "B. 0℃", "C. 1℃", "D. 4℃"]', 'B', extract(epoch from now())::bigint),
('q038', '自然', '动物世界', '蜗牛用哪里爬行？', '["A. 脚", "B. 腹足", "C. 翅膀", "D. 尾巴"]', 'B', extract(epoch from now())::bigint),
('q039', '自然', '植物天地', '种子发芽不需要？', '["A. 水", "B. 阳光", "C. 适宜温度", "D. 土壤（可无土栽培）"]', 'D', extract(epoch from now())::bigint),
('q040', '自然', '天气气候', '台风通常在哪个季节较多？', '["A. 春季", "B. 夏秋季", "C. 冬季", "D. 全年一样"]', 'B', extract(epoch from now())::bigint),
('q041', '地理', '中国地理', '中国的首都是？', '["A. 上海", "B. 北京", "C. 西安", "D. 南京"]', 'B', extract(epoch from now())::bigint),
('q042', '地理', '世界地理', '世界上面积最大的国家是？', '["A. 中国", "B. 美国", "C. 俄罗斯", "D. 加拿大"]', 'C', extract(epoch from now())::bigint),
('q043', '地理', '中国地理', '长江是中国第几长河？', '["A. 第一", "B. 第二", "C. 第三", "D. 第四"]', 'A', extract(epoch from now())::bigint),
('q044', '地理', '世界地理', '赤道穿过哪个大洲？', '["A. 欧洲", "B. 亚洲", "C. 非洲", "D. 北美洲"]', 'C', extract(epoch from now())::bigint),
('q045', '地理', '中国地理', '黄河发源于哪个省？', '["A. 西藏", "B. 青海", "C. 四川", "D. 甘肃"]', 'B', extract(epoch from now())::bigint),
('q046', '地理', '世界地理', '世界上最高的山峰是？', '["A. 泰山", "B. 珠穆朗玛峰", "C. 黄山", "D. 华山"]', 'B', extract(epoch from now())::bigint),
('q047', '地理', '中国地理', '台湾岛位于中国的？', '["A. 东海", "B. 南海", "C. 黄海", "D. 渤海"]', 'A', extract(epoch from now())::bigint),
('q048', '地理', '世界地理', '地球上有几大洲？', '["A. 5 个", "B. 6 个", "C. 7 个", "D. 8 个"]', 'C', extract(epoch from now())::bigint),
('q049', '地理', '中国地理', '长城东起哪里？', '["A. 嘉峪关", "B. 山海关", "C. 居庸关", "D. 玉门关"]', 'B', extract(epoch from now())::bigint),
('q050', '地理', '世界地理', '亚马逊河位于哪个大洲？', '["A. 非洲", "B. 南美洲", "C. 北美洲", "D. 亚洲"]', 'B', extract(epoch from now())::bigint),
('q051', '科学', '物理常识', '光在空气中传播速度约为？', '["A. 每秒 3 万千米", "B. 每秒 30 万千米", "C. 每秒 300 万千米", "D. 每秒 3 千万千米"]', 'B', extract(epoch from now())::bigint),
('q052', '科学', '物理常识', '声音在哪种介质中传播最快？', '["A. 空气", "B. 水", "C. 钢铁", "D. 真空"]', 'C', extract(epoch from now())::bigint),
('q053', '科学', '生物常识', '人体有多少块骨头？', '["A. 约 200 块", "B. 约 206 块", "C. 约 250 块", "D. 约 300 块"]', 'B', extract(epoch from now())::bigint),
('q054', '科学', '物理常识', '杠杆省力的原理是？', '["A. 力臂越长越省力", "B. 力臂越短越省力", "C. 与力臂无关", "D. 永远不省力"]', 'A', extract(epoch from now())::bigint),
('q055', '科学', '生物常识', '血液中负责输送氧气的是？', '["A. 白细胞", "B. 红细胞", "C. 血小板", "D. 血浆"]', 'B', extract(epoch from now())::bigint),
('q056', '科学', '物理常识', '水的沸点大约是？', '["A. 90℃", "B. 100℃", "C. 110℃", "D. 120℃"]', 'B', extract(epoch from now())::bigint),
('q057', '科学', '生物常识', '人体最大的器官是？', '["A. 心脏", "B. 肝脏", "C. 皮肤", "D. 肺"]', 'C', extract(epoch from now())::bigint),
('q058', '科学', '物理常识', '磁铁的两极叫做？', '["A. 东极和西极", "B. 南极和北极", "C. 正极和负极", "D. 阳极和阴极"]', 'B', extract(epoch from now())::bigint),
('q059', '科学', '生物常识', '植物通过什么吸收水分？', '["A. 叶子", "B. 根", "C. 花", "D. 果实"]', 'B', extract(epoch from now())::bigint),
('q060', '科学', '物理常识', '彩虹的形成与什么有关？', '["A. 光的反射", "B. 光的折射和反射", "C. 只有折射", "D. 热胀冷缩"]', 'B', extract(epoch from now())::bigint),
('q061', '科学', '太空探索', '地球绕太阳转一圈大约是？', '["A. 30 天", "B. 半年", "C. 一年", "D. 两年"]', 'C', extract(epoch from now())::bigint),
('q062', '科学', '太空探索', '月球是地球的？', '["A. 恒星", "B. 行星", "C. 卫星", "D. 彗星"]', 'C', extract(epoch from now())::bigint),
('q063', '科学', '太空探索', '太阳系中最大的行星是？', '["A. 土星", "B. 木星", "C. 火星", "D. 地球"]', 'B', extract(epoch from now())::bigint),
('q064', '科学', '太空探索', '人类首次登月是在哪一年？', '["A. 1965", "B. 1969", "C. 1975", "D. 1980"]', 'B', extract(epoch from now())::bigint),
('q065', '科学', '太空探索', '北斗七星属于哪个星座？', '["A. 大熊座", "B. 小熊座", "C. 猎户座", "D. 天鹅座"]', 'A', extract(epoch from now())::bigint),
('q066', '动物', '动物世界', '狗是由什么动物驯化来的？', '["A. 狼", "B. 狐狸", "C. 豺", "D. 熊"]', 'A', extract(epoch from now())::bigint),
('q067', '动物', '动物世界', '猫头鹰主要在什么时候活动？', '["A. 白天", "B. 夜晚", "C. 清晨", "D. 黄昏"]', 'B', extract(epoch from now())::bigint),
('q068', '动物', '动物世界', '海豚用哪里呼吸？', '["A. 鳃", "B. 肺", "C. 皮肤", "D. 嘴"]', 'B', extract(epoch from now())::bigint),
('q069', '动物', '动物世界', '变色龙变色是为了？', '["A. 好看", "B. 伪装和调节体温", "C. 吓唬敌人", "D. 吸引伴侣"]', 'B', extract(epoch from now())::bigint),
('q070', '动物', '动物世界', '蚂蚁靠什么传递信息？', '["A. 叫声", "B. 触角和气味", "C. 跳舞", "D. 写字"]', 'B', extract(epoch from now())::bigint),
('q071', '动物', '动物世界', '大象的鼻子有什么作用？', '["A. 只能闻", "B. 呼吸、吸水、抓东西等", "C. 只能喝水", "D. 装饰"]', 'B', extract(epoch from now())::bigint),
('q072', '动物', '动物世界', '啄木鸟为什么啄树？', '["A. 玩耍", "B. 找虫子吃、筑巢", "C. 磨嘴", "D. 打招呼"]', 'B', extract(epoch from now())::bigint),
('q073', '动物', '动物世界', '鲸鱼是鱼吗？', '["A. 是", "B. 不是，是哺乳动物", "C. 是两栖动物", "D. 是爬行动物"]', 'B', extract(epoch from now())::bigint),
('q074', '动物', '动物世界', '兔子最爱吃什么？', '["A. 肉", "B. 草和蔬菜", "C. 粮食", "D. 鱼"]', 'B', extract(epoch from now())::bigint),
('q075', '动物', '动物世界', '蜘蛛有几条腿？', '["A. 4 条", "B. 6 条", "C. 8 条", "D. 10 条"]', 'C', extract(epoch from now())::bigint),
('q076', '计算机', '基础常识', '计算机的「CPU」主要功能是？', '["A. 存储", "B. 运算和控制", "C. 显示", "D. 输入"]', 'B', extract(epoch from now())::bigint),
('q077', '计算机', '基础常识', '1 KB 等于多少字节？', '["A. 100", "B. 512", "C. 1024", "D. 1000"]', 'C', extract(epoch from now())::bigint),
('q078', '计算机', '基础常识', '互联网的英文是？', '["A. Intranet", "B. Internet", "C. Web", "D. Net"]', 'B', extract(epoch from now())::bigint),
('q079', '计算机', '基础常识', '电脑「复制」的快捷键通常是？', '["A. Ctrl+A", "B. Ctrl+C", "C. Ctrl+V", "D. Ctrl+X"]', 'B', extract(epoch from now())::bigint),
('q080', '计算机', '基础常识', '「粘贴」的快捷键通常是？', '["A. Ctrl+A", "B. Ctrl+C", "C. Ctrl+V", "D. Ctrl+Z"]', 'C', extract(epoch from now())::bigint),
('q081', '计算机', '基础常识', '二进制中 1+1 等于？', '["A. 0", "B. 1", "C. 2", "D. 10"]', 'D', extract(epoch from now())::bigint),
('q082', '计算机', '基础常识', '「WWW」的含义是？', '["A. 局域网", "B. 万维网", "C. 电子邮件", "D. 文件传输"]', 'B', extract(epoch from now())::bigint),
('q083', '计算机', '基础常识', 'U 盘属于什么设备？', '["A. 输入设备", "B. 输出设备", "C. 存储设备", "D. 显示设备"]', 'C', extract(epoch from now())::bigint),
('q084', '计算机', '基础常识', '「软件」指的是？', '["A. 键盘鼠标", "B. 程序和数据", "C. 显示器", "D. 主机箱"]', 'B', extract(epoch from now())::bigint),
('q085', '计算机', '基础常识', '「保存」的快捷键通常是？', '["A. Ctrl+N", "B. Ctrl+S", "C. Ctrl+O", "D. Ctrl+P"]', 'B', extract(epoch from now())::bigint),
('q086', '历史', '文化常识', '春节是农历几月初几？', '["A. 正月初一", "B. 腊月初八", "C. 五月初五", "D. 八月十五"]', 'A', extract(epoch from now())::bigint),
('q087', '历史', '文化常识', '端午节纪念的是？', '["A. 孔子", "B. 屈原", "C. 李白", "D. 杜甫"]', 'B', extract(epoch from now())::bigint),
('q088', '历史', '文化常识', '中秋节在农历几月？', '["A. 五月", "B. 七月", "C. 八月", "D. 九月"]', 'C', extract(epoch from now())::bigint),
('q089', '历史', '文化常识', '「岁寒三友」指哪三种植物？', '["A. 梅兰竹", "B. 松竹梅", "C. 桃李杏", "D. 梅菊兰"]', 'B', extract(epoch from now())::bigint),
('q090', '历史', '文化常识', '「文房四宝」不包括？', '["A. 笔", "B. 墨", "C. 纸", "D. 书"]', 'D', extract(epoch from now())::bigint),
('q091', '地理', '中国地理', '中国最长的河流是？', '["A. 黄河", "B. 长江", "C. 珠江", "D. 黑龙江"]', 'B', extract(epoch from now())::bigint),
('q092', '地理', '世界地理', '太平洋是五大洋中？', '["A. 最小的", "B. 最大的", "C. 最浅的", "D. 最冷的"]', 'B', extract(epoch from now())::bigint),
('q093', '科学', '生物常识', '人体有多少颗恒牙？', '["A. 28 颗", "B. 30 颗", "C. 32 颗", "D. 36 颗"]', 'C', extract(epoch from now())::bigint),
('q094', '科学', '物理常识', '摩擦力与接触面粗糙程度的关系是？', '["A. 越光滑越大", "B. 越粗糙越大", "C. 无关", "D. 有时大有时小"]', 'B', extract(epoch from now())::bigint),
('q095', '自然', '天气气候', '云是由什么组成的？', '["A. 烟", "B. 小水滴或冰晶", "C. 灰尘", "D. 气体"]', 'B', extract(epoch from now())::bigint),
('q096', '篮球', '规则常识', '篮球比赛中「24 秒」规则指？', '["A. 一节时长", "B. 进攻方持球不得超过 24 秒", "C. 暂停时长", "D. 换人时限"]', 'B', extract(epoch from now())::bigint),
('q097', '篮球', '球星故事', 'NBA 总决赛采用几场几胜制？', '["A. 3 场 2 胜", "B. 5 场 3 胜", "C. 7 场 4 胜", "D. 9 场 5 胜"]', 'C', extract(epoch from now())::bigint),
('q098', '动物', '动物世界', '鸟类的祖先是？', '["A. 哺乳动物", "B. 恐龙类爬行动物", "C. 鱼类", "D. 两栖动物"]', 'B', extract(epoch from now())::bigint),
('q099', '计算机', '基础常识', '「IP 地址」的作用大致是？', '["A. 标识一台设备在网络中的位置", "B. 存储文件", "C. 显示网页", "D. 发送邮件"]', 'A', extract(epoch from now())::bigint),
('q100', '综合', '综合知识', '「知识就是力量」这句名言与哪位科学家有关？', '["A. 牛顿", "B. 培根", "C. 爱因斯坦", "D. 达尔文"]', 'B', extract(epoch from now())::bigint)
ON CONFLICT (id) DO NOTHING;
